### ISSUE TITLE
Invalid property in "library.properties" breaks build process in arduino-cli

### ISSUE THREAD

**Issue by SNL5943** [LennartHennigs/Button2#15]
Hi, 

I was having a trouble with [Arduino-CLI ](https://github.com/arduino/arduino-cli) when using TTGO-TDisplay for the target board, this board's example is using Button2 lib, the example seems working fine in Arduino IDE (the regular with GUI one we are using) but Arduino-CLI is not. When I built with CLI, It showed:
> fatal error: Button2.h: No such file or directory

Eventually it is there in the library directory. 

I did a further investigation and figured it out that was not the Arduino-cli causing the problem but the Button2 library, there is an invalid property in "library.properties" of it: `includes=ButtonCallback.h` . IMO, Arduino-cli expected 'ButtonCallback.h' but in the Sketch has `#include = "Button2.h"` and 'Buttoncallback.h' is not in the lib directory also. I have refered this [document](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata).

I deleted the property from the file and everything worked normally again.

**Comment by LennartHennigs** [comment]
Hey, 
thank you for pointing this out!
I'll remove this from the file in the next release.
Cheers!
