### ISSUE TITLE
How to handle initial button state?

### ISSUE THREAD

**Issue by giannoug** [LennartHennigs/Button2#28]
Consider the following button:
`Button2 bigRedButton = Button2(bigRedButtonPin, INPUT_PULLUP, false, false);`

For some weird reason, the button is pressed while the Arduino reboots. This doesn't fire any callbacks. I have tried `setPressedHandler`, `setReleasedHandler` and `setChangedHandler`. Since the button is not active low, shouldn't it trigger on boot? It works fine if I release and press it after booting.

**Comment by LennartHennigs** [comment]
Hey George,  I will try to replicate this issue.

**Comment by LennartHennigs** [comment]
Hey George, I have a hard time duplicating the behavior you describe. 
But please checkout the latest version via GitHub and give it a try. I updated how I set the Initial values of the `state` and `prev_state` vars. Maybe this will solve your issue.
