### ISSUE TITLE
Decalring SetHandler time

### ISSUE THREAD

**Issue by rassalrich** [LennartHennigs/Button2#38]
Hi I am trying to use your library for my code, everything seems to be working on compile. However, I am getting an error code saying src\main.cpp: In function 'void setup()':
src\main.cpp:89:27: error: 'click' was not declared in this scope
   buttonA.setClickHandler(click);

I am using the multiple buttons part from your code

**Comment by LennartHennigs** [comment]
Hey, did you define a function called click() in your source code? 
This is what the compiler is looking for.

**Comment by rassalrich** [comment]
No, I haven't defined the same, since your example code had no part defining the same. How would you advice to have the same defined?

**Comment by LennartHennigs** [comment]
Please take another look at the example:

examples/MultipleButtons/MultipleButtons.ino

Below the loop() there IS the click() function defined.
