### ISSUE TITLE
getType() with Long Click Detected

### ISSUE THREAD

**Issue by ryancasler** [LennartHennigs/Button2#41]
The press type of that is stored for the button is not updated until the button is released isn't it?   I ran into a bit of a problem trying to use a multi-type handler with longClickDetected.  It would always report the previous click type until I did 2 in a row.  But the same setup worked perfectly if I had a separate handler.  That's when it occurred to me that the press type might not be updated until the button is released, therefore causing my problem.  Might be something to mention as another difference between longClickHandler and longClickDetectedHanlder.
But I love the new custom handler function!   I am planning on using a Seesaw GPIO expander from Adafruit for a project and the only thing that has been holding me back is needing to code all of the button handler timing manually.  This is wonderful!  Thank you!

**Comment by LennartHennigs** [comment]
Hey @ryancasler,

thanks for the feedback.

> That's when it occurred to me that the press type might not be updated until the button is released, therefore causing my problem. Might be something to mention as another difference between longClickHandler and longClickDetectedHandler.

And yes, that is the case. 
Good point though, I will mention it in the example. Thank you.

> But I love the new custom handler function! 
Glad you like it. Was an idea from the community. Wouldn't have thought of it myself. 
But used it shortly afterwards for the M5 Stack. :-)
