### ISSUE TITLE
Suggestion to add options for Led Buttons

### ISSUE THREAD

**Issue by mrNo0b** [LennartHennigs/Button2#48]
Would be nice to have option to control button with LED, option to set pin for button LED and have function to turn it on/off, remember state, different led flash patterns for different press types etc.
Maybe make inheriting class from Button2, for example Button2Led...
![ledbutton](https://user-images.githubusercontent.com/12209347/207692650-0dc02407-a02e-4da5-9e8e-8ba59b7d5fc3.png)

**Comment by LennartHennigs** [comment]
Hey, 
thanks for the feedback. 
I understand your request but I think other dedicated LED libraries already provide these functions already, e.g. [ezLED](https://github.com/ArduinoGetStarted/led).  I'd use one of these to do stuff with an LED button. 
This keeps the code of this library focused on button handling and additions can easily be added through other libs.

I follow a similar approach in my [rotary encoder library](https://github.com/LennartHennigs/ESPRotary) where I decided against implementing any button handling features even though encoders usually have a button. I combine these two classes in my own code.
