### ISSUE TITLE
SerialBT issue

### ISSUE THREAD

**Issue by daveparisee** [LennartHennigs/Button2#5]
Hi!
I'm working on esp32 and I need SerialBT lib AND button2.. button2 work great if I comment out SerialBT command in sketch.
As soon as I uncomment SerialBT command, button2 refuse to work. SerialBT is working.

There's no delay is code.

**Comment by krasniykrd** [comment]
If u working with esp32 use RTOS tasks for non blocking actions!

**Comment by LennartHennigs** [comment]
I'll take some time for me to reproduce this. I'll have to dig up an ESP32 and give it a try.
I usually use ESP8266s so I don't have one at hand.

**Comment by LennartHennigs** [comment]
Sorry, I don't  really understand your request. 
In the constructor you can define the button mode  (INPUT or INPUT_PULLUP).
Does this not solve your problem?
If not, could you please elaborate a bit? thx.

**Comment by daveparisee** [comment]
Buttons2 and serialBT does not work together..

**Comment by krasniykrd** [comment]
> Buttons2 and serialBT does not work together..

On esp32 all works....

**Comment by LennartHennigs** [comment]
It might have been, that the loop got stuck because of no delays(). Added one to the `Button2` loop.
