### ISSUE TITLE
.pio/libdeps/seeed_xiao_esp32c3/Button2/src/Button2.cpp:186:20: error: 'touchRead' was not declared in this scope

### ISSUE THREAD

**Issue by gknops** [LennartHennigs/Button2#50]
Looks like the Seeed Studio xiao_esp32c3 triggers `ARDUINO_ARCH_ESP32` (sounds reasonable) but does not support `touchRead()`?

**Comment by LennartHennigs** [comment]
Hey, thanks for pointing this out. 
Could you please check your version of Button2. I recently removed touch_read from  the lib and only use it in the examples.

**Comment by gknops** [comment]
Confirmed, working fine with current library version. Sorry for the noise, and thanks for Button2! Long-time user in several projects.
