### ISSUE TITLE
Interrupt wdt timeout on CPU1

### ISSUE THREAD

**Issue by ifengchao** [LennartHennigs/Button2#52]
Hi, 
when i run the example ESP32TimerInterrupt.ino, it crashed when i click the button, every time.

here the modified code:
#define BUTTON_PIN 35
btn.begin(BUTTON_PIN, INPUT_PULLDOWN, false);

Other code are not modified.

Here's the log:

click
Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1). 

Core  1 register dump:
PC      : 0x4008c1f2  PS      : 0x00060335  A0      : 0x8008b166  A1      : 0x3ffbf0ec  
A2      : 0x3ffb8314  A3      : 0x3ffb81a4  A4      : 0x00000004  A5      : 0x00060323  
A6      : 0x00060323  A7      : 0x00000001  A8      : 0x3ffb81a4  A9      : 0x00000018  
A10     : 0x3ffb81a4  A11     : 0x00000018  A12     : 0x00000004  A13     : 0x00060323  
A14     : 0x007bf328  A15     : 0x003fffff  SAR     : 0x0000000a  EXCCAUSE: 0x00000006  
EXCVADDR: 0x00000000  LBEG    : 0x4008786d  LEND    : 0x4008787d  LCOUNT  : 0xfffffffe  
Core  1 was running in ISR context:
EPC1    : 0x400de797  EPC2    : 0x00000000  EPC3    : 0x00000000  EPC4    : 0x00000000

Backtrace: 0x4008c1ef:0x3ffbf0ec |<-CORRUPTED

Core  0 register dump:
PC      : 0x4008c38b  PS      : 0x00060035  A0      : 0x8008ad8f  A1      : 0x3ffbea4c  
A2      : 0x3ffbf328  A3      : 0xb33fffff  A4      : 0x0000abab  A5      : 0x00060023  
A6      : 0x00060021  A7      : 0x0000cdcd  A8      : 0x0000abab  A9      : 0xffffffff  
A10     : 0x3ffc307c  A11     : 0x00000000  A12     : 0x3ffc3078  A13     : 0x00000007  
A14     : 0x007bf328  A15     : 0x003fffff  SAR     : 0x0000001d  EXCCAUSE: 0x00000006  
EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  

It seems the function "onTimer()" costs too much time? But only "btn.loop();"

Any help will be appreciated!

**Comment by LennartHennigs** [comment]
Hey, I'd recommend to use the loop functions - since attaching it to an interrupt could result in hiccups. I'll state that more clearly in the comments. 

The size of the code you use in the function, among other things, could cause this, e.g. millis() don't work as "time has stopped" in interrupt functions.

**Comment by ifengchao** [comment]
OK, I've tried other button lib with interupt method, the same result.  Finally turned to loop method, since esp32 has two cores,choose one core to run the button loop works fine for me.
