### ISSUE TITLE
Long press is not reported in polling mode

### ISSUE THREAD

**Issue by IvanBayan** [LennartHennigs/Button2#54]
Long press is not reported in polling mode.
If you uncomment commented part in this example: https://github.com/LennartHennigs/Button2/blob/master/examples/ButtonLoop/ButtonLoop.ino condition
```          
case long_click: 
            Serial.println("looong");
            break;
```
will never met.

**Comment by LennartHennigs** [comment]
Thank for for the PR!
It fixes the issue!
