### ISSUE TITLE
Advices for implementing a speed-sensitive button-press control

### ISSUE THREAD

**Issue by paaspaas00** [LennartHennigs/Button2#62]
@LennartHennigs  Hi, in my project I'd like to implement a button that when pressed for long, the value displayed in the screen (say, an integer) increases, slowly at the beginning and then faster, according to how long I've been pressing the button.
How can I implement that with this library? Is there an example of this? Is `setLongClickDetectedRetriggerable()` the function to use?
Btw, can it be added as a feature?

**Comment by LennartHennigs** [comment]
Hey, 
to you questions:

1. yes, I'd use a retriggerable long press for your use case.
2. no, won't be added as a feature, as this is not really a missing feature of the class but a matter of using it in a solution.
