### ISSUE TITLE
setStateHandler Functions

### ISSUE THREAD

**Issue by woodenplastic** [LennartHennigs/Button2#63]
Hi,

is there a way to  call functions with values like:

   button1.setButtonStateFunction(buttonstate(i)). 

So i can use one state function for different buttons?

All the best and love
Adrian

**Comment by LennartHennigs** [comment]
Hey Adrian, 

you can assign the same callback function for different buttons. 
Currently you cannot pass additional parameters to the callback.

But all callback include a reference to the source button. This allows you to differentiate between the buttons.
See [MultiHandlerTwoButtons](https://github.com/LennartHennigs/Button2/blob/master/examples/MultiHandlerTwoButtons/MultiHandlerTwoButtons.ino).

Is this what you had in mind?
