### ISSUE TITLE
Use hall sensor instead button

### ISSUE THREAD

**Issue by jaksatomovic** [LennartHennigs/Button2#65]
I am wondering is it possible to add hall sensor instead button on input pin and use this lib to detect single double tripple magnet readings?

**Comment by LennartHennigs** [comment]
hey @jaksatomovic,
I don't have a hall sensor at hand. but google told me that you can hook it up to a digital pin.
So yes, I think there is a pretty good chance, that this works.
Let me know, if you try it out. :-)
