### ISSUE TITLE
clear assigned functions

### ISSUE THREAD

**Issue by Nagymadar** [LennartHennigs/Button2#7]
In some cases it would be helpful to clear all assigned functions and variables.
Example: menu handling where after a click new functions must be assigned, but all older have to be cleared. It can be done right now by manually assigning NULL to all of them, but a simple clear function would solve it. 
Another option to delete buttons and create new ones as this is done when an instance is created. But that needs more resources. Any suggestions?

**Comment by LennartHennigs** [comment]
so you'd like a clearAll() function that removes all callback functions?

**Comment by LennartHennigs** [comment]
I named the function `reset()`.
