### ISSUE TITLE
[question] Is it compatible with all microcontrollers having an Arduino framework implementation?

### ISSUE THREAD

**Issue by paaspaas00** [LennartHennigs/Button2#75]
Like the STM32 ecc

**Comment by LennartHennigs** [comment]
Most likely yes, as I only use digitalRead. But as I don't have ALL the microcontrollers I am not able to test this.

**Comment by paaspaas00** [comment]
Wow thank you! That's amazing! You can add this not as a nice selling point in the readme 👍 👍
