### ISSUE TITLE
add fun

### ISSUE THREAD

**Issue by liuzewen2** [LennartHennigs/Button2#78]
`
String Button2::getName() const {
  return Name;
}

/////////////////////////////////////////////////////////////////

void Button2::setName(String newName) {
  Name = newName;
}
`

**Comment by LennartHennigs** [comment]
Hey,
is question to add a name field to the button class.
I am not a fan of naming them because you have no guarantee that the name will be unique.
Please use the `getID()` and `setID()` functions instead to map names to them, if needed. Or use the ID as an identifier.
